# Site settings
title: Yash Khandelwal
description: description
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://yashsk8.github.io" # the base hostname & protocol for your site
source              : .
destination         : ./_site
collections_dir     : .
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output          : true