# Where things are
source              : .
destination         : ./_site
collections_dir     : .
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output          : true